### ISSUE TITLE
Document how to use LSP server with Helix

### ISSUE THREAD

**Issue by toolness** [toolness/abasic#6]
```toml
[[language]]

name = "abasic"
scope = "source.abasic"
file-types = ["bas"]
language-servers = ["abasic-lsp"]
roots = []

[language-server.abasic-lsp]
command = "abasic-lsp"
```
